enum ErrorsConst {
    ERROR_CREATE_NEW_PROJECT = 'ERROR_CREATE_NEW_PROJECT',
    ERROR_EDIT_PROJECT = 'ERROR_EDIT_PROJECT',
    ERROR_CREATE_NEW_TASK = 'ERROR_CREATE_NEW_TASK',
    ERROR_LOGIN_USER = 'ERROR_LOGIN_USER',
    ERROR_REGISTER_USER = 'ERROR_REGISTER_USER',
}

export default ErrorsConst;