export interface Task {
    title: string,
    brief?: string, 
    guidelines: string,
    time: number,
    categoryTask: Array<string>,
    taskUsers: Array<string>,
    halfTimeReport: boolean,
    projectName: string,
    projectId: string,
    isFinish: boolean,
    isActive?: boolean,
    taskTime: number,
    id: string,
    weight: number,
    _id: string,
}

export interface InitialTaskData {
    title: string,
    brief: string,
    time: number,
    guidelines: string,
    categoryTask: string[],
    projectId: string,
    projectName: string,
    halfTimeReport: boolean,
    taskUsers: string[],
    isFinish: boolean,
    taskTime: number,
    id: string,
    weight: number,
    _id: string,
}