enum ProjectsConst {
    FETCH_ALL_PROJECTS = 'FETCH_ALL_PROJECTS',
    FETCH_DATA = 'FETCH_DATA',
    CREATE_PROJECT = 'CREATE_PROJECT',
    GET_DETAILS_PROJECT = 'GET_DETAILS_PROJECT',
    EDIT_PROJECT = 'EDIT_PROJECT',
    ADD_TASK_TO_PROJECT = 'ADD_TASK_TO_PROJECT',
}

export default ProjectsConst;