enum TasksConst {
    SELECT_TYPE_OF_TASK = 'SELECT_TYPE_OF_TASK',
    GET_EMPTY = 'GET_EMPTY',
    CREATE_NEW_TASK = 'CREATE_NEW_TASK',
    START_TASK = 'START_TASK',
    STOP_TASK = 'STOP_TASK',
    FETCH_ALL_TASKS = 'FETCH_ALL_TASKS',
    CLOSE_TASK = 'CLOSE_TASK',
    UPDATE_TASK = 'UPDATE_TASK',
    FETCH_DATA = 'FETCH_DATA',
}

export default TasksConst;